# Generated by Django 4.2.11 on 2024-04-30 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_author_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 4, 30, 21, 22, 42, 265970), verbose_name='Опубликована'),
        ),
    ]
